name: riverpod
description: >
  A simple way to access state from anywhere in your application
  while robust and testable.
version: 0.10.0
homepage: https://riverpod.dev
repository: https://github.com/rrousselGit/river_pod

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  meta: ">=1.1.8 <2.0.0"
  collection: ">=1.14.12 <2.0.0"
  freezed_annotation: ">=0.11.0 <1.0.0"
  state_notifier: ">= 0.5.0 <1.0.0"

dev_dependencies:
  mockito: ^4.1.0
  test: ^1.14.2
  freezed: ">=0.11.0 <1.0.00"
  build_runner: ^1.8.1
  trotter: ^1.2.0
  test_coverage: ^0.4.1
