name: flutter_riverpod
description: >
  A simple way to access state from anywhere in your application
  while robust and testable.
version: 0.11.1
homepage: https://riverpod.dev
repository: https://github.com/rrousselGit/river_pod

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">= 1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.12
  riverpod: ^0.11.0
  state_notifier: ">= 0.5.0 <1.0.0"
  meta: ^1.1.8

dev_dependencies:
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  riverpod:
    path: ../../packages/riverpod
